# Имя твоего workflow. Будет отображаться на вкладке Actions в GitHub
name: .NET CI - Сборка и тестирование

# Условие запуска workflow
on:
  # Запускать при push в ветку main
  push:
    branches: [ test ]
  # Запускать при создании pull request в ветку main
  pull_request:
    branches: [ test ]

# Задачи, которые нужно выполнить
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонирование репозитория (без изменений)
    - name: Клонирование репозитория
      uses: actions/checkout@v4

    # 2. Установка .NET 8 (без изменений)
    - name: Установка .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    # 3. Восстановление зависимостей
    - name: Восстановление зависимостей
      run: dotnet restore TelegramWordBot.sln

    # 4. Сборка проекта
    # ИЗМЕНЕНИЕ: Собираем в конфигурации 'Debug', так как тесты запускаются в ней.
    - name: Сборка проекта
      run: dotnet build TelegramWordBot.sln --configuration Debug --no-restore

    # 5. Запуск тестов
    # ИЗМЕНЕНИЕ: Явно указываем проект для тестирования, чтобы избежать проблем.
    # Путь взят из твоего лога.
    - name: Запуск тестов
      run: dotnet test TelegramWordBot/TelegramWordBot.Tests/TelegramWordBot.Tests.csproj --configuration Debug --no-build --verbosity normal
